name: build_test_docker
      
on:
  push:
    paths:
      - '.github/workflows/build_test_docker.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        id: build-image
        run: |
          docker build -t test_app:1.0 .
