name: pass_variable_between_steps

      
on:
  push:
    paths:
      - '.github/workflows/pass_data_between_steps.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "test_var=step 2" >> $GITHUB_ENV
          echo "${{ env.action_state }}" # This will output 'yellow'
          echo "test var ${{ env.test_var }}" # Can't access this var in this step
      - name: step 3
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
          echo "test var ${{ env.test_var }}" # Both variables are now available
