name: python-coverage
      
on:
  pull-request:
    paths:
      - '.github/workflows/python_coverage.yml'
      - 'python/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install coverage
      - run: cd python && coverage run -m unittest test_sample_lib
      - run: ls
