
name: tag_own_repo
on:
  push:
    paths:
      - '.github/workflows/tag_own_repo.yml'
jobs:
  old-git-container:
    runs-on: ubuntu-latest
    container: python:3.4
    steps:
      - uses: actions/checkout@v2
      - run: git --version
      - run: git tag -a 1.2.0 -m "Tagged with old git 2.old"
  new-git-container:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - uses: actions/checkout@v2
      - run: git --version
      - run: git tag -a 1.3.0 -m "Tagged with new git"
